linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - unparam
    - prealloc
    - bodyclose
    - exportloopref
    - gosec
    - dupl

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: pr-reviewer
  misspell:
    locale: US
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G404  # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
